### ISSUE TITLE
onended events are inconsistent

### ISSUE THREAD

**Issue by tambien** [TONEnoTONE/Tone.js#48]
They seem to work only on certain browsers in certain situations. This can cause bugs like the transport not being able to stop and restart in FireFox.

Replace bindings to the native `onended` events with a `setTimeout` instead.

**Comment by tambien** [comment]
All sources use setTimeout to time the `onended` event

**Comment by cristiano-belloni** [comment]
@tambien - This makes the behaviour of `onended` inconsistent when `playbackTime !== 1`. Maybe this has been resolved in Firefox?

**Comment by tambien** [comment]
Related to #301
