### ISSUE TITLE
Dynamically set loop boundaries while playing Tone.Player

### ISSUE THREAD

**Issue by taylorbf** [TONEnoTONE/Tone.js#49]
With Tone.Player, I notice that after using `.setLoopStart()` and `.setLoopEnd()`, the changes only go into effect when I execute `.start()` to restart the player.

It would be great to change this so that `.setLoopStart()` etc all actually affect `Player._source` so that users can dynamically change granular playback position without restarting the player. Or, maybe this is outside of the design goals for the Player?

**Comment by tambien** [comment]
that's a good suggestion. i'll add that. (or feel free to send a PR). 

it's definitely part of the design goals. i want to support and eventually add a granular synth so that would be a necessary thing to have in the Player.
