### ISSUE TITLE
TypeScript support for r4?

### ISSUE THREAD

**Issue by tambien** [TONEnoTONE/Tone.js#50]
Big API changes in r4: moving most of the `setSomething` / `getSomething` methods over to ES5 getter/setter interfaces. 

Overall it makes the library much more consistent, readable, and expressive. Hopefully this isn't a problem with TypeScript. 

@lukephills

**Comment by lukephills** [comment]
Great, yes should make it a lot more concise. I'll update this week

**Comment by tambien** [comment]
Merged those changes. Thanks Luke!

**Comment by lukephills** [comment]
Great, no worries! 

I will do another update to that soon as new Typescript v1.4 can handle union types, ie: 

Tone.Buffer(url: AudioBuffer | string).
