### ISSUE TITLE
Convolver not loading

### ISSUE THREAD

**Issue by lukephills** [TONEnoTONE/Tone.js#54]
I've got an issue with the Convolver in r4. Seems like the convolver buffer isn't being set.

`this.Effect = new Tone.Convolver("../Assets/ImpulseResponses/teufelsberg01.wav");`

`this.Effect._convolver.buffer = null`

**Comment by tambien** [comment]
You're right! It was not being set correctly when loaded through a URL. I've just pushed a fix to the dev branch.

**Comment by lukephills** [comment]
Great thanks for fixing. And nice work on the new es5 getters and setters. This way seems a lot more user friendly.
