### ISSUE TITLE
PitchShift

### ISSUE THREAD

**Issue by taylorbf** [TONEnoTONE/Tone.js#56]
Feature request: PitchShift effect, i.e. that could be applied to an input source / media element source node. If you ever have time for it, this would be awesome!

**Comment by lukephills** [comment]
Yes this would be amazing!

**Comment by tambien** [comment]
This would be amazing, but i really don't know how i could accomplish this with the current Web Audio API and high performance / no ScriptProcessorNode philosophy of Tone. 

I'm going to close this and we can potentially reopen it when the AudioWorker node arrives and this might seem more feasible. 

For now, you can pitch shift samples, but this is simple playbackrate pitch shifting and not really full-blown pitch shifting.
