### ISSUE TITLE
Tone.Transport tick listeners

### ISSUE THREAD

**Issue by hiddedejong** [TONEnoTONE/Tone.js#62]
**Feature request**
Enable the transport to send its ticks to other/multiple destinations. A function like 'setListener' adds a callback which will be executed at each tick. 

**Why?**
I'd like to create multiple 'smaller' transports (with their own loop points), but have them in the same BPM as the global transport. Creating a new clock for each transport seems unnecessary and using the ticks of the main transport would be perfect!

Thank you!

**Comment by tambien** [comment]
Thanks for the PR Hidde. I see your point, but i like that the ticks are abstracted away. I may make them more or less frequent at a later date (probably more frequent), but that would break any applications that are built with `setListener`. There is also currently no API for for getting how long a tick is or how many ticks are in a quarter note, and without exposing those as well, a user of the Listener callback would just be getting callbacks "very often", but without a sense of how often it actually is which makes it hard to create any kind of clock or metronome based on those callbacks. 

Maybe a `setInterval` with a very small number be sufficient for your needs? I was considering adding `ticks` to `Tone.Time` so you could do something like: 

```
Tone.Transport.setInterval(function(time){
  //stuff
}, "1i");
```

which would give you a callback every tick, but that has the same breaking issues if I make the ticks more frequent. 

I think the preferred method for creating your own metronomes that still follow the tempo curves of the Transport is to sync multiple Tone.Clocks `frequency` attributes to the Transport with `syncSignal`. The Clock's `frequency` attribute is a `Tone.Signal` so the Transport's `syncSignal` method to keep all of those frequencies in sync with the Transport's bpm. You could additionally use `syncSource` to automatically call those Clock's `start` and `stop` methods when the Transport is started and stopped.

**Comment by hiddedejong** [comment]
I understand. In my case, changing the pulse per quarter wouldn't really matter, because I calculate the amount of ticks by putting a `Tone.Time` value in `Tone.Transport._toTicks()`. (I'm sorry..) Using `setInterval` with ticks would work for me since it would do the same as `setListener`.

Would it be an idea to be able to set the (input) PPQ manually, like MIDI? I actually used the `Tone.Clock` solution at first, but I thought it would make more sense to use the Transport's ticks since it would save oscillators, syncing and ScriptProcessors.

**Comment by tambien** [comment]
maybe letting people set the ticks manually is the way to go. if i open up PPQ in the API, i'll definitely add `ticks` to Tone.Time. 

thanks again for the feedback.
