### ISSUE TITLE
Tone.Clock.stop() without a second argument; onend is undefined

### ISSUE THREAD

**Issue by hiddedejong** [TONEnoTONE/Tone.js#65]
When calling `stop` (without a second argument) on a `Tone.Clock`, it tries to execute `onend` but it's undefined. 

Chrome throws the following error:
`Uncaught TypeError: onend is not a function`

It breaks the whole function containing the `stop` call.

A jsfiddle example:
http://jsfiddle.net/rn76Ly4n/1/

**Comment by tambien** [comment]
The method was documented as a non-optional second argument, but i'll remove the callback from the `stop` method and switch it to an instance member called `onended` so it's more similar to the sources. it's easy enough.
