### ISSUE TITLE
MonoSynth Objects on iOS Mobile

### ISSUE THREAD

**Issue by cn-yn** [TONEnoTONE/Tone.js#67]
Been going around in circles trying to figure out why this sketch I was making with Tone.js was giving me grief on mobile (using Chrome/Safari on an iPhone) - realized if I swapped plain Oscillators in instead of MonoSynths then it worked.
Ended up rebuilding the MonoSynth chain, I think pretty much piece-by-piece, just in my sketch, and it works. But if I swap in MonoSynths again it breaks. Tested this on a completely simplified 'just touch the canvas' and it plays a note type of scenario and it seems to hold true - works fine on desktop, no output on mobile if it's using MonoSynth. Noticed the Synth Examples don't seem to play on iOS mobile either so wanted to notify that there could be something wrong. I'm really new to programming so I could just be doing something wrong though.

**Comment by cn-yn** [comment]
Please disregard, I got one to work. Strangely still can't get it to work in a super basic - touch the canvas to make a sound scenario -- an oscillator into an amp envelope into a filter, with a scalable envelope controlling the filter, works fine but sub in the MonoSynth and there's no mobile output. It's working in a more complicated little sketch though so I'm thinking it must be something on my end. Sorry for the false alarm.

**Comment by cn-yn** [comment]
Ah figured it out - on mobile the synth triggerAttack alone doesn't unmute the output (it has oscillator start as part of the method so I'm not sure why that is), if you include an oscillator and .start() it alongside the synth that can unmute the output and you're good to go. So you can add an oscillator at -99 volume and that will open things up without intruding on your sounds.

**Comment by tambien** [comment]
That's what i thought was the problem, but i didn't get a chance to test it out. I've included a helper method `Tone.startMobile()` which does exactly what you describe. It creates and oscillator and plays it. You have to bind that method to a `touchstart` event for mobile devices to start making sound. 

I don't know why that got lost from the examples. I will be sure to fix that in the next release. Good catch.

**Comment by cn-yn** [comment]
Got it, thanks - I saw the `Tone.startMobile()` method as I was combing through the library trying to figure out what was going on, I tried to utilize it but I was just doing it wrong - and I thought `triggerAttack()` would unmute things anyway if it was tied to a `touchstart` event -- all squared now though thank you!
