### ISSUE TITLE
Recording general output/Creating Visualizer

### ISSUE THREAD

**Issue by hamesetawa** [TONEnoTONE/Tone.js#71]
I'm trying to make a simple DAW. I need to be able to export all output, or record it to an MP3. I also want to set up a visualizer to all output.

How would I do this? Is there a call to get all output and convert it into an MP3? Or to see all audio output's volume and frequencies?

**Comment by tambien** [comment]
There is no built-in method for recording the output, but you could bind a recording node to the master output and that would record everything in your application using a library like [recorder.js](https://github.com/mattdiamond/Recorderjs). 

As far as metering volume, you could connect the Tone.Master to an instance of Tone.Meter. For frequency/amplitude data, i would recommend the native web audio AnalyserNode. It's quite simple to use. You could hook it up in the same way.
