### ISSUE TITLE
Understanding the Timeline

### ISSUE THREAD

**Issue by HighOnDrive** [TONEnoTONE/Tone.js#72]
Why do the Note objects returned by Tone.Note.parseScore(Score) have a timelineID that is just a simple integer, instead of the time as it was encoded? In the Tone.Note.parseScore(Score) function it looks like it grabs noteDescription[0] and assigns it to the time var. 

Wondering where this time description goes and why note objects in the console just show a timelineID with a simple integer value? Where is the timeline suppose to be, is it just the notes array returned by Tone.Note.parseScore(Score)? Likely the time description is also expanded if it is a expression, where is the end result of the expansion?

**Comment by HighOnDrive** [comment]
Still looking into this and hoping to learn more about what happens to the parsed descriptions. I see that time can be represented in the following ways, including seconds. Yet what looks like a sequential ordering of the timelineID values in the returned notes array is not clear to me and likely is not seconds :)

Once I understand I can see a potential to build a full score, have some ideas for this I can share.

**Comment by tambien** [comment]
The note class is just a thin wrapper around the Transport's `setTimeline` method. and `parseScore` just sets up a bunch of scheduled notes on the timeline. 

The timelineID is an internal tracker which is useful for removing an event from the timeline. I was following a similar API to the native browser `setTimeout` which returns a unique ID which can be used with `clearTimeout`. The actual timing of the event is stored in "ticks" privately in the Transport class and not exposed.
